# Generated by Django 3.0.5 on 2020-04-13 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='username',
        ),
        migrations.AlterModelTable(
            name='comment',
            table='comments',
        ),
    ]
